#!/bin/sh

install_config() {
	gcl https://github.com/seciurte/nvim-config/ ~
	cp -r ~/nvim-config/lua ~/.config/nvim/
	rm -rf ~/nvim-config
	rm -f install
}

for res in $(find ~ -name .config); do
	if [ res == "./.config" ]; then
		install_config() exit 0
	fi
done
